### ISSUE TITLE
Notice of license infringment

### ISSUE THREAD

**Issue by HitLuca** [XanaduAI/quantum-neural-networks#4]
Opened this issue to inform the owner that action can be taken in order to take down this repository, https://github.com/llSourcell/The-Neural-Qubit , in which code from this repo has been taken from and license removed.

**Comment by vinsis** [comment]
I also reported the same issue to GitHub and this is the reply I got:

> If you are the copyright holder and want to have the content removed, you have the option of filing a DMCA takedown notice. Instructions, examples, and policy details are available here:
>
> https://help.github.com/articles/dmca-takedown-policy/
>
> https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/
>
> If you're not the copyright holder, your best bet would be to contact the owner of the content and let them decide if they'd like to take action.

Just letting the owners of this repo know.

**Comment by HitLuca** [comment]
The owners don't seem interested in taking action sadly

**Comment by josh146** [comment]
We have left an issue here: https://github.com/llSourcell/The-Neural-Qubit/issues/5
