### ISSUE TITLE
Files not found error

### ISSUE THREAD

**Issue by arshad7878** [XanaduAI/quantum-neural-networks#7]
Thanks for such a fabulous working. I want to run the script but facing error messages. When I try to run data_processor.py file it gives an error message of file not found. creditcard.csv 
When I try to run fraud_detection.py file it also gives an error message of file not found. creditcard_genuine_1.csv
Do we have to create these files at our own or these are found at some other place.

**Comment by arshad7878** [comment]
Found the solution...
https://www.kaggle.com/mlg-ulb/creditcardfraud
download creditcard.csv from the above link

**Comment by co9olguy** [comment]
Yes, that's right @arshad7878. Glad you found the dataset :)
